name: playit
services:
  palworld-server:
    image: ghcr.io/docker-collection/payit:latest
    restart: unless-stopped
    container_name: playit
    volumes:
      - /DATA/AppData/playit:/app/config
    network_mode: bridge
    deploy:
      resources:
        reservations:
          memory: 4096M

x-casaos:
  architectures:
    - amd64
    - arm64
  main: playit
  store_app_id: playit.gg
  category: Network
  author: Stradios
  developer: zealous_kaity
  icon: https://raw.githubusercontent.com/Stradios/CasaOS-AppStore-Games-servers/main/Apps/Playit/icon.png
  screenshot_link:
    - https://playit.gg/build/_assets/logo-NYRFHLA6.png
  thumbnail: https://playit.gg/build/_assets/logo-NYRFHLA6.png
  description:
    en_us: Get started with hosting your game Servers playiy.gg
  tagline:
    en_us: Easily hosting your game Servers playiy.gg
  title:
    en_us: playiy.gg
  tips:
    before_install:
      en_us: |
        Get started with hosting your game Servers playiy.gg
  port_map: ''
  scheme: http
  index: /