name: payit
services:
  playit:
    cpu_shares: 90
    command: []
    container_name: payit.gg
    deploy:
      resources:
        limits:
          memory: 15901M
    hostname: playit
    image: ghcr.io/docker-collection/payit:latest
    labels:
      icon: https://raw.githubusercontent.com/Stradios/CasaOS-AppStore-Games-servers/main/Apps/Playit.gg/icon.png
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData
        target: /app/config
    ports: []
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: playit.gg
  icon: https://raw.githubusercontent.com/Stradios/CasaOS-AppStore-Games-servers/main/Apps/Playit.gg/icon.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: zealous_kaity
  title:
    custom: payit